### ISSUE TITLE
Seems that doesn't work with new "Material Design" apps

### ISSUE THREAD

**Issue by Kaijun** [MohammadAG/Xposed-Tinted-Status-Bar#147] opened 2014-11-12 19:18 UTC
e.g. new Gmail, new Google Store, Inbox, such apps which are following "Material Design", can't be recognised.

hope could fix that :smile:

**Comment by GermainZ** [comment] 2014-11-12 19:22
Duplicate of #142, #144, #145, #139, #138, #134 and #129.

**Closed as completed by GermainZ** 2014-11-12 19:22 UTC
