### ISSUE TITLE
Issue with material design updates

### ISSUE THREAD

**Issue by muqtada** [MohammadAG/Xposed-Tinted-Status-Bar#134] opened 2014-10-23 10:48 UTC
Tinted status bars do not work in Some of the google apps which got updated with material design recently like latest 'Google Play Music'.

Tinting worked perfectly for the previous version of google play music

**Comment by Nxt3** [comment] 2014-10-24 20:45
This has already been reported.

**Comment by GermainZ** [comment] 2014-10-29 17:11
Duplicate of #129.

**Closed as completed by GermainZ** 2014-10-29 17:11 UTC
