### ISSUE TITLE
Notification Area Clock Colour Chnages bug

### ISSUE THREAD

**Issue by harbir** [MohammadAG/Xposed-Tinted-Status-Bar#98] opened 2014-08-11 20:17 UTC
Sometimes the notifications area top clock colour changes from white to black and is difficult to see ,its quite annoying please see and fix 
thx

**Comment by GermainZ** [comment] 2014-08-22 00:12
Closing this since there isn't enough information (how to reproduce it? when does it happen? what ROM? TSB version? etc.), but this commit might fix it: b2beb7944f44d874776131b6178063c3879add33 (already in 1.8.9.3)

**Closed as completed by GermainZ** 2014-08-22 00:12 UTC
