### ISSUE TITLE
Constant System UI Crashes

### ISSUE THREAD

**Issue by bgiesing** [MohammadAG/Xposed-Tinted-Status-Bar#103] opened 2014-08-24 14:17 UTC
No matter what ROM I use on my Google Nexus 7 (grouper), I get so many system ui crashes that it is impossible to use the device!

I am currently on AOSPA but I have tried Mahdi ROM.

I also think it could possibly be a conflict with the CM theme engine.

**Comment by bgiesing** [comment] 2014-08-24 14:18
Oops forgot to attach log... https://docs.google.com/file/d/0B3DhUCRnvErzRm1GSzNiOXZrMUU/edit?usp=docslist_api

**Comment by GermainZ** [comment] 2014-08-24 15:12
You're filtering the logcat for "systemui" (or similar) which basically makes it useless. Please filter it for "AndroidRuntime" instead, or not at all.

**Comment by bgiesing** [comment] 2014-08-24 15:21
Here is a log filtered for AndroidRuntime.

https://docs.google.com/file/d/0B3DhUCRnvErzb2lsWEtCT0ZtNWs/edit?usp=docslist_api

Sincerely,
Brandon Giesing

**Comment by GermainZ** [comment] 2014-08-24 15:29
You're running out of memory, the crash isn't caused by TSB (at least not directly). Does it not happen when TSB is disabled?

**Comment by bgiesing** [comment] 2014-08-24 15:34
It happens quite a bit when TSB is enabled but it also happens when it is
disabled, just less frequently.

I thought it was a problem with my CM theme Veu so I emailed the dev and
they said it might be TSB.

Sincerely,
Brandon Giesing

**Comment by GermainZ** [comment] 2014-08-24 15:38
That's possible, but as you said, TSB only makes it happen sooner. I'm closing this issue since it's a duplicate of #19.

**Closed as completed** 2014-08-24 15:38 UTC
