### ISSUE TITLE
Google Play Store 5.0.37

### ISSUE THREAD

**Issue by IvanSantos** [MohammadAG/Xposed-Tinted-Status-Bar#142] opened 2014-11-07 11:50 UTC
Hello.
In Google Play Store 4.9.13 this module works great with all the colors, but with the 5.0.37 version doesnt auto detect the colors (and it's kinda boring setting the colors to every different tab.

Is there a way or a fix to this problema?

Best regards,
Ivan Santos

**Comment by GermainZ** [comment] 2014-11-08 14:48
Duplicate of #129.

**Closed as completed by GermainZ** 2014-11-08 14:48 UTC
