### ISSUE TITLE
will we get new update on google play store tinted status bar?

### ISSUE THREAD

**Issue by bradjyoon** [MohammadAG/Xposed-Tinted-Status-Bar#139] opened 2014-10-29 12:05 UTC
So reacently I got new google play store and got whole material design however what I noticed is that tinted status bar no longer works on google play store. Will you guys please update that a soon as possible?

**Comment by bradjyoon** [comment] 2014-10-29 12:06
I'm talking about status bar. And I have galaxy s4 build number ends with NG6

**Comment by GermainZ** [comment] 2014-10-29 17:11
Duplicate of #129.

**Closed as completed by GermainZ** 2014-10-29 17:11 UTC
